@{
    # Module manifest for K.PSGallery.ManifestVersioning
    # Generated by: GrexyLoco
    # Generated on: 10/12/2025

    RootModule = 'K.PSGallery.ManifestVersioning.psm1'
    ModuleVersion = '0.0.1'
    GUID = '13df5873-962f-4431-95d2-01dec5569f1b'
    Author = 'GrexyLoco'
    CompanyName = 'GrexyLoco'
    Copyright = '(c) 2025 GrexyLoco. All rights reserved.'
    Description = 'PowerShell module for updating module manifest (.psd1) versions with Git integration'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry
    FunctionsToExport = @(
        'Update-ModuleManifestVersion'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry
    AliasesToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('PowerShell', 'Module', 'Manifest', 'Version', 'Automation', 'DevOps', 'PSGallery')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/GrexyLoco/K.PSGallery.ManifestVersioning/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/GrexyLoco/K.PSGallery.ManifestVersioning'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'Initial release of K.PSGallery.ManifestVersioning module'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        } # End of PSData hashtable
    } # End of PrivateData hashtable
}